# 应用服务 WEB 访问端口
server:
  port: 8888

spring:
  # 应用名称
  application:
    name: jlja
  mvc:
    #    hiddenmethod:
    #      filter:
    #        enabled: true
    view:
      prefix: /
      suffix: .html
    static-path-pattern: /**
    resources:
      static-locations:
        - classpath:/templates/
        - classpath:/static/
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/erahub_jlja?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
#  redis:
#    host: 127.0.0.1
#    port: 6379
##    pcmassword:
#    jedis:
#      pool:
#        max-idle: 8
#        min-idle: 0
#        max-active: 8
#        max-wait: -1ms
#    database: 0
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/**Mapper.xml

# 配置redis连接
shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379
#    password: 123456

# 配置
erahub:
  jwt:
    # 加密秘钥
    secret: f4e2e45682348f86b67cde852c0f9eb5
    # token有效时长，7天，单位秒
    expire: 10
    header: Authorization